version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: golang_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend-golang
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      ENV: development
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/golang_db?authSource=admin
      FRONTEND_ORIGIN: http://localhost:5173
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./client-reactjs
      dockerfile: Dockerfile
    environment:
        VITE_API_URL: /api
    expose:
      - "80"
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:

volumes:
  mongodb_data:
